import yweather

client = yweather.Client()

Argentina = client.fetch_woeid('Argentina')
Australia = client.fetch_woeid('Australia')
Brazil = client.fetch_woeid('Brazil')
Canada = client.fetch_woeid('Canada')
China = client.fetch_woeid('China')
Germany = client.fetch_woeid('Germany')
France = client.fetch_woeid('France')
India = client.fetch_woeid('India')
Indonesia = client.fetch_woeid('Indonesia')
Italy = client.fetch_woeid('Italy')
Japan = client.fetch_woeid('Japan')
Mexico = client.fetch_woeid('Mexico')
Russia = client.fetch_woeid('Russia')
Saudi_Arabia = client.fetch_woeid('Saudi Arabia')
South_Africa = client.fetch_woeid('South Africa')
South_Korea = client.fetch_woeid('South Korea')
Spain = client.fetch_woeid('Spain')
Turkey = client.fetch_woeid('Turkey')
UK = client.fetch_woeid('United Kingdom')
US = client.fetch_woeid('United States')



print ('Argentina :', Argentina)
print ('Australia :', Australia)
print ('Brazil :', Brazil)
print ('Canada :', Canada)
print ('China :', China)
print ('Germany :', Germany)
print ('France :', France)
print ('India :', India)
print ('Indonesia :', Indonesia)
print ('Italy :', Italy)
print ('Japan :', Japan)
print ('Mexico :', Mexico)
print ('Russia :', Russia)
print ('Saudi_Arabia :', Saudi_Arabia)
print ('South_Africa :', South_Africa)
print ('South_Korea :', South_Korea)
print ('Spain :', Spain)
print ('Turkey :', Turkey)
print ('UK :', UK)
print ('US :', US)